### ISSUE TITLE
Cannot find file "pattern_refine" and "target_generation2"

### ISSUE THREAD

**Issue by Zhichao-Zhang** [lcinrain/6subpattern#1]
Hi,

I encountered an issue while running main_6subpattern.py. This script imports modules named pattern_refine and target_generation2, and it calls several functions from these modules in subsequent operations. However, it seems that these modules are not present in the source code repository.

Here's the error I received:

```python
Traceback (most recent call last):
  File "/root/6subpattern/main_6subpattern.py", line 7, in <module>
    from pattern_refine import patterns_refine_conservative,read_refine_conservative_pattern
ModuleNotFoundError: No module named 'pattern_refine'
``` 

Could you please check if these files were omitted from the repository? Thank you for your assistance!

**Comment by lcinrain** [comment]
we have updated the codes
----- 原始邮件 -----
发件人：zhichao ***@***.***>
收件人：lcinrain/6subpattern ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[lcinrain/6subpattern] Cannot find file "pattern_refine" and "target_generation2" (Issue #1)
日期：2024年07月18日 11点04分


Hi,
I encountered an issue while running main_6subpattern.py. This script imports modules named pattern_refine and target_generation2, and it calls several functions from these modules in subsequent operations. However, it seems that these modules are not present in the source code repository.
Here's the error I received:
Traceback (most recent call last):
  File "/root/6subpattern/main_6subpattern.py", line 7, in <module>
    from pattern_refine import patterns_refine_conservative,read_refine_conservative_pattern
ModuleNotFoundError: No module named 'pattern_refine'
Could you please check if these files were omitted from the repository? Thank you for your assistance!
